### Obtener datos de todos los documentos, sin los atributos de tipo blob
GET http://localhost:3000/api/casos/documentos/


### Obtener datos de todos los documentos de un caso, sin los atributos de tipo blob
GET http://localhost:3000/api/casos/documentos/por-caso/2


### Obtener un documento por id
GET http://localhost:3000/api/casos/documentos/2


### Guardar un nuevo documento
POST http://localhost:3000/api/casos/documentos/
Content-Type: multipart/form-data; boundary=----boundary1234

------boundary1234
Content-Disposition: form-data; name="archivo"; filename="nombre-archivo.pdf"
Content-Type: application/pdf

< ruta-al-archivo

------boundary1234
Content-Disposition: form-data; name="nombre"

DNI Carla Mansilla2

------boundary1234
Content-Disposition: form-data; name="id_caso"

1

------boundary1234--


### Dar de baja un documento
PATCH http://localhost:3000/api/casos/documentos/deactivate/2
