###
GET http://localhost:3000/api/casos/abogados-casos/

###
GET http://localhost:3000/api/casos/abogados-casos/2

###
POST http://localhost:3000/api/casos/abogados-casos/
Content-Type: application/json

{
    "id_abogado": 4,
    "id_caso": 2
}

###
PATCH http://localhost:3000/api/casos/abogados-casos/vincular/3
Content-Type: application/json

{
    "id_abogado": 3
}

###
PATCH http://localhost:3000/api/casos/abogados-casos/desvincular/2/4


###
PATCH http://localhost:3000/api/casos/abogados-casos/deactivate/10

