@id = id
@id_caso = id

###
GET http://localhost:3000/api/casos/comentarios/{{id_caso}}


###
POST http://localhost:3000/api/casos/comentarios/
Content-Type: application/json

{
  "id_caso": {{id}},
  "comentario": "También hay que hacer un análisis de calidad del formato del documento"
}


###
POST http://localhost:3000/api/casos/comentarios/7
Content-Type: application/json

{
  "id_caso": {{id}},
  "comentario": "Si, estoy de acuerdo"
}


###
DELETE http://localhost:3000/api/casos/comentarios/{{id}}
