###
GET http://localhost:3000/api/misc/noticias

###
GET http://localhost:3000/api/misc/noticias/6

###
POST http://localhost:3000/api/misc/noticias
Content-Type: application/json

{
  "titulo": "Título ejemplo de una noticia",
  "cuerpo": "Cuerpo ejemplo de una noticia",
  "fecha_publicacion": "2025-01-25",
  "fecha_vencimiento": "2025-02-26"
}

###
PUT http://localhost:3000/api/misc/noticias/7
Content-Type: application/json

{
  "titulo": "Título ejemplo de una noticia",
  "cuerpo": "Cuerpo ejemplo de una noticia",
  "fecha_publicacion": "2024-01-18",
  "fecha_vencimiento": "2027-06-12"
}

###
PATCH http://localhost:3000/api/misc/noticias/desactivate/6
