@id = id

###
GET http://localhost:3000/api/casos/notas/

###
GET http://localhost:3000/api/casos/notas/{{id}}

###
POST http://localhost:3000/api/casos/notas/
Content-Type: application/json

{
  "id_caso": {{id}},
  "id_abogado": {{id}},
  "titulo": "Nota ejemplo 2",
  "descripcion": "Descripción de nota ejemplo 2"
}

###
PUT http://localhost:3000/api/casos/notas/{{id}}
Content-Type: application/json

{
  "id_caso": {{id}},
  "id_abogado": {{id}},
  "titulo": "Nota ejemplo 2",
  "descripcion": "Descripción modificada"    
}

###
DELETE http://localhost:3000/api/casos/notas/{{id}}
