###
GET http://localhost:3000/api/casos/notas/

###
GET http://localhost:3000/api/casos/notas/6

###
POST http://localhost:3000/api/casos/notas/
Content-Type: application/json

{
    "id_caso": 6,
    "id_abogado": 4,
    "titulo": "Nota ejemplo 2",
    "descripcion": "Descripción de nota ejemplo 2"
}

###
PUT http://localhost:3000/api/casos/notas/6/4/2025-02-27T15:26:27
Content-Type: application/json

{
    "titulo": "Nota ejemplo 2 actualizada 2 veces"
}

###
DELETE http://localhost:3000/api/casos/notas/6/4/2025-02-27T15:26:27

