###
POST http://localhost:3000/api/informes/ingresos/
Content-Type: application/json

{
  "mes": "2025-02"
}

###
POST http://localhost:3000/api/informes/caso/
Content-Type: application/json

{
  "id_caso": 2
}


###
POST http://localhost:3000/api/informes/desempenio/
Content-Type: application/json

{
  "mes": "2024-08",
  "id_abogado": 3
}

