@id = id

###
POST http://localhost:3000/api/informes/ingresos/
Content-Type: application/json

{
  "mes": "yyyy-mm"
}

###
POST http://localhost:3000/api/informes/caso/
Content-Type: application/json

{
  "id_caso": {{id}}
}


###
POST http://localhost:3000/api/informes/desempenio/
Content-Type: application/json

{
  "mes": "yyyy-mm",
  "id_abogado": {{id}}
}

