###
GET http://localhost:3000/api/usuarios/secretarios/


###
GET http://localhost:3000/api/usuarios/secretarios/6


###
POST http://localhost:3000/api/usuarios/secretarios
Content-Type: application/json

{
  "nombre": "Natasha",
  "apellido": "Romanoff",
  "email": "blackwidow@avengers.com",
  "telefono": "+0156489754",
  "contrasena": "mypassword",
  "tipo_doc": "DNI",
  "nro_doc": "27569854",
  "turno_trabajo": "mañana"
}


###
PATCH http://localhost:3000/api/usuarios/secretarios/27
Content-Type: application/json

{
  "telefono": "+5493415698745"
}
