@id = id
@codigo_cancelacion = codigo

### Obtener todos los turnos otorgados por un abogado para la fecha actual o futuras.
GET http://localhost:3000/api/turnos/{{id}}


### Reservar un turno como cliente
POST http://localhost:3000/api/turnos/
Content-Type: application/json

{
  "id_horario_turno": {{id}},
  "fecha_turno": "2025-01-31",
  "id_cliente": {{id}}
}


### Reservar un turno como visitante
POST http://localhost:3000/api/turnos/
Content-Type: application/json

{
  "id_horario_turno": {{id}},
  "fecha_turno": "2025-08-31",
  "nombre": "Jorgelina",
  "telefono": "3419478416",
  "email": "jorgelina@gomez.com"
}


### Cancelar la reserva de un turno
PATCH http://localhost:3000/api/turnos/{{id}}/cancelar/{{codigo_cancelacion}}
