###
GET http://localhost:3000/api/casos/recordatorios/

###
GET http://localhost:3000/api/casos/recordatorios/2

###
POST http://localhost:3000/api/casos/recordatorios/2/2
Content-Type: application/json

{
    "fecha_hora_limite": "2025-02-23T12:00:00",
    "descripcion": "Descripción de recordatorio ejemplo 1"
}

###
PUT http://localhost:3000/api/casos/recordatorios/4
Content-Type: application/json

{
    "descripcion": "Descripción de recordatorio actualizada ejemplo 1"
}

###
DELETE http://localhost:3000/api/casos/recordatorios/4

