@id = id

###
GET http://localhost:3000/api/usuarios/abogados/


###
GET http://localhost:3000/api/usuarios/abogados/disponibles


###
GET http://localhost:3000/api/usuarios/abogados/disponibles/caso/{{id}}

### 
GET http://localhost:3000/api/usuarios/abogados/{{id}}/especialidades

###
GET http://localhost:3000/api/usuarios/abogados/{{id}}


###
POST http://localhost:3000/api/usuarios/abogados
Content-Type: application/json

{
  "nombre": "Juan",
  "apellido": "Pérez",
  "email": "juanperez@example.com",
  "telefono": "+5491123456789",
  "contrasena": "miContraseña123",
  "tipo_doc": "DNI",
  "nro_doc": "12345678",
  "foto": "datos-archivo",
  "matricula": "55889",
  "id_rol": {{id}},
  "especialidades": [{{id}}]
}


###
PATCH http://localhost:3000/api/usuarios/abogados/{{id}}
Content-Type: application/json

{
  "nombre": "Juan Bautista",
  "apellido": "Rodriguez",
  "matricula": "62358",
  "id_rol": {{id}},
  "telefono": "1234",
  "especialidades": [{{id}},{{id}},{{id}}]
}
