###
GET http://localhost:3000/api/casos/

###
GET http://localhost:3000/api/casos/encurso/

###
GET http://localhost:3000/api/casos/2

###
POST http://localhost:3000/api/casos/
Content-Type: application/json

{
  "id_cliente": 7,
  "id_especialidad": 4,
  "descripcion": "Descripción de un caso de prueba",
}


###
PUT http://localhost:3000/api/casos/5
Content-Type: application/json

{
  "id_cliente": 5,
  "id_especialidad": 3,
  "descripcion": "Descripción de un caso de prueba con una actualización"
}

###
PUT http://localhost:3000/api/casos/casos/end/5
Content-Type: application/json

{
  "cant_jus": 1000,
  "num_cuotas": 10,
  "fecha_primer_cobro": "2025-05-05",
  "frecuencia_pago": "mensual",
  "forma_cobro": "efectivo"
}

###
PATCH http://localhost:3000/api/casos/deactivate/1
