###
GET http://localhost:3000/api/casos/casos/

###
GET http://localhost:3000/api/casos/casos/encurso/

###
GET http://localhost:3000/api/casos/casos/2

###
POST http://localhost:3000/api/casos/casos/
Content-Type: application/json

{
  "id_cliente": 7,
  "id_especialidad": 4,
  "descripcion": "Descripción de un caso de prueba",
  "monto_caso": null
}


###
PUT http://localhost:3000/api/casos/casos/5
Content-Type: application/json

{
  "id_cliente": 5,
  "id_especialidad": 3,
  "descripcion": "Descripción de un caso de prueba con una actualización",
  "estado": "En curso",
  "monto_caso": null
}

###
PATCH http://localhost:3000/api/casos/casos/deactivate/7