###
GET http://localhost:3000/api/casos/cuotas/

###
GET http://localhost:3000/api/casos/cuotas/nearest/5

###
PATCH http://localhost:3000/api/casos/cuotas/5/7
Content-Type: application/json

{
  "forma_cobro": "Efectivo"
}

